E:
  Eq1:
  - 0.0
  - 0.0
  - 1.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  - 1.0
  - 1.0
  Eq2:
  - 1.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  - 1.0
  - 0.0
  - 0.0
  - 0.0
nbcomp:
- 2.0
- 2.0
- 3.0
- 3.0
- 2.0
- 2.0
nbEq: 2
nbg: 6.0
